[project]
name = "expense-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fridtjof Pernack" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.0.0",
    "ollama>=0.6.2",
    "opencv-contrib-python>=4.10.0",
    "paddleocr>=3.7.0",
    "paddlepaddle==3.2.2",
    "pypdfium2>=4.30.0",
]

[project.scripts]
expense-tracker = "expense_tracker:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
